# Generated by Django 5.2 on 2025-08-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('low', '軽度'), ('medium', '中程度'), ('high', '重度')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('keyword', 'キーワード'), ('spam', 'スパム'), ('harassment', 'ハラスメント'), ('inappropriate', '不適切なコンテンツ'), ('copyright', '著作権')], max_length=20)),
                ('pattern', models.TextField()),
                ('action', models.CharField(choices=[('warn', '警告'), ('timeout', 'タイムアウト'), ('ban', 'バン'), ('delete', '削除'), ('flag', 'フラグ')], max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warn', '警告'), ('timeout', 'タイムアウト'), ('ban', 'バン'), ('delete_message', 'メッセージ削除'), ('delete_video', '動画削除'), ('hide_video', '動画非表示')], max_length=20)),
                ('target_type', models.CharField(choices=[('user', 'ユーザー'), ('message', 'チャットメッセージ'), ('video', '動画'), ('comment', 'コメント')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.moderationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'ユーザー'), ('video', '動画'), ('comment', 'コメント'), ('message', 'チャットメッセージ')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('spam', 'スパム'), ('harassment', 'ハラスメント'), ('inappropriate', '不適切なコンテンツ'), ('copyright', '著作権侵害'), ('fake', '偽情報'), ('other', 'その他')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', '保留中'), ('investigating', '調査中'), ('resolved', '解決済み'), ('dismissed', '却下')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('low', '軽度'), ('medium', '中程度'), ('high', '重度')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
