# Generated by Django 5.2 on 2025-08-29 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stream_id', models.CharField(max_length=100, unique=True)),
                ('stream_key', models.CharField(max_length=200)),
                ('ingest_url', models.URLField()),
                ('playback_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', '作成済み'), ('live', 'ライブ中'), ('ended', '終了'), ('error', 'エラー')], default='created', max_length=20)),
                ('privacy', models.CharField(choices=[('public', '公開'), ('unlisted', '限定公開'), ('private', '非公開')], default='public', max_length=20)),
                ('is_recording', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
                ('subscriber_only_chat', models.BooleanField(default=False)),
                ('viewer_count', models.IntegerField(default=0)),
                ('peak_viewers', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('streams', models.ManyToManyField(blank=True, related_name='tags', to='streaming.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='streaming.stream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stream', 'user', 'ip_address')},
            },
        ),
    ]
