# Generated by Django 5.2 on 2025-09-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='bitrate',
            field=models.CharField(choices=[('500', '500 kbps'), ('1000', '1 Mbps'), ('2500', '2.5 Mbps'), ('5000', '5 Mbps'), ('8000', '8 Mbps'), ('12000', '12 Mbps')], default='2500', max_length=10),
        ),
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streaming.streamcategory'),
        ),
        migrations.AddField(
            model_name='stream',
            name='enable_donations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='framerate',
            field=models.IntegerField(default=30, help_text='FPS'),
        ),
        migrations.AddField(
            model_name='stream',
            name='mature_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='quality',
            field=models.CharField(choices=[('360p', '360p (低画質)'), ('480p', '480p (標準)'), ('720p', '720p (HD)'), ('1080p', '1080p (フルHD)'), ('1440p', '1440p (2K)'), ('2160p', '2160p (4K)')], default='720p', max_length=10),
        ),
    ]
