# Generated by Django 5.2 on 2025-09-03 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('streaming', '0002_stream_bitrate_stream_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatstamp')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='streaming.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stream', '-created_at'], name='streaming_s_stream__0c7fc7_idx'), models.Index(fields=['stamp', '-created_at'], name='streaming_s_stamp_i_26798f_idx')],
            },
        ),
    ]
