# Generated by Django 5.2 on 2025-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_streamreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='obs_overlay_enabled',
            field=models.BooleanField(default=True, help_text='OBSオーバーレイ機能の有効/無効'),
        ),
        migrations.AddField(
            model_name='stream',
            name='obs_overlay_token',
            field=models.CharField(blank=True, help_text='OBS用オーバーレイアクセストークン', max_length=64),
        ),
    ]
