# Generated by Django 5.2 on 2025-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_stream_obs_overlay_enabled_stream_obs_overlay_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='obs_overlay_anonymous',
            field=models.BooleanField(default=False, help_text='ユーザー名を非表示にする（ニコニコ風匿名モード）'),
        ),
    ]
