# Generated by Django 5.2 on 2025-09-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_stream_obs_overlay_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='obs_overlay_enabled',
        ),
    ]
